title: Katharos Technology
description: Making awesome stuff.

# Not used yet
# heroText: Pure Innovation

sections:
  - type: content
    title: Katharos Tech Consulting
    lead: >
      Contract us to bring your cloud architecture to the next level.
  - type: contact-form
    title: Contact Us
    lead: Let's get it done.
    turnstileSiteKey: 0x4AAAAAABXiVbLyKqAQitnM
    contactBackend: https://ktech-consulting-contact.deno.dev/contact
