title: Kadima Solutions
description: Business technology consulting - Forward Thinking. Lasting Solutions.

# # Not used yet
heroText: Kadima Solutions

sections:
  - type: content
    title: Business Technology Consulting
    lead: Forward Thinking. Lasting Solutions.
  - type: contact-form
    title: Contact Us
    lead: Let's get it done
    turnstileSiteKey: 0x4AAAAAABfEjQ0GMKXNduDd
    contactBackend: https://ktech-consulting-contact.deno.dev/contact
