title: Kadima Solutions
description: Business technology consulting - Forward Thinking. Lasting Solutions.

# # Not used yet
# heroText: Pure Innovationkk

sections:
  - type: content
    title: Kadima Solutions
    lead: Business Technology Consulting<br /><br />Forward Thinking. Lasting Solutions.
  - type: contact-form
    title: Contact Us
    lead: Let's get it done
    turnstileSiteKey: 0x4AAAAAABXiVbLyKqAQitnM
    contactBackend: https://ktech-consulting-contact.deno.dev/contact
