title: Katharos Technology
description: Making awesome stuff.

# Not used yet
# heroText: Pure Innovation

sections:
  - type: content
    title: Katharos Technology
    lead: >
      <span class="text-primary">Pure Innovation</span>.
  - type: compatibility
    id: projects
    title: Projects
    lead: >
      Things we're working on.
    lists:
      - items:
          - icon: logomark
            title: Chord 9
            url: http://chord9.app
          - icon: logomark
            title: KTech Studio
            url: https://ktech.studio
